routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'HomeController@index')->name('home');


/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::get('profile', 'UserProfileController@show')->middleware('auth')->name('profile.show');
Route::post('profile', 'UserProfileController@update_avatar')->middleware('auth')->name('profile.update');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


/*
|--------------------------------------------------------------------------
| Blog Routes
|--------------------------------------------------------------------------
*/

//  Index
Route::get('blog', 'Blog\BlogController@index')->name('blog.index');

//  Single
Route::get('blog/{slug}', 'Blog\BlogController@single')->where('slug', '[\w\d\-\_]+')->name('blog.single');


/*
 * | Posts
|--------------------------------------------------------------------------
*/

//  Resource
Route::resource('posts', 'Blog\PostController');


//  Index
//Route::get('blog/posts', 'Blog\PostController@index')->name('blog.posts.index');

//  Create
Route::get('create', 'Blog\PostController@create');

//  Store
Route::get('store', function () {
    return view('blog.posts.store');
});

//  Show
Route::get('show', function () {
    return view('blog.posts.show');
});


//

Route::get('webshop', function () {
    return view('webshop.index');
});


/*
 * | Comments
|--------------------------------------------------------------------------
*/

Route::post('comments/{post_id}', ['uses' => 'Blog\CommentsController@store', 'as' =>'comments.store']);
Route::get('comments/{id}/edit', ['uses' => 'Blog\CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}', ['uses' => 'Blog\CommentsController@update', 'as' => 'comments.update']);
Route::get('comments/{id}/delete', ['uses' => 'Blog\CommentsController@delete', 'as' => 'comments.delete']);
Route::delete('comments/{id}', ['uses' => 'Blog\CommentsController@destroy', 'as' => 'comments.destroy']);



/*
 * | Categories
|--------------------------------------------------------------------------
*/

Route::resource('categories', 'Blog\CategoryController', ['except' => ['create']]);



/*
 * | Tags
|--------------------------------------------------------------------------
*/

Route::get('tags/find', 'Blog\TagController@find');
Route::resource('tags', 'Blog\TagController', array('except' => array('create', 'find')));

Route::get('pages/check_slug', 'SlugController@check')->name('pages.check_slug');



// Ajax Routes
Route::get('entry', function () {
    return view('auth.entry');
});

Route::get('profile-menu', function(){
    return view('partials.menu.profile-menu');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('stylesheets')
    <link rel="stylesheet" href="css/owlCarousel/owl.carousel.css">
@endsection

@section('scripts')
    <script src="{{ asset('js/owlCarousel/owl.carousel.js') }}"></script>
    <script src="{{ asset('js/scripts/owl-customs.js') }}"></script>
@endsection

@section('classes')
    class="home"
@endsection

@section('content')
    <div class="grid-container">
        <div class="grid-x">

            <div class="cell small-24 collapsable">
                <div class="grid-x grid-block">
                    <!-- Top left -->
                    <div class="cell top-left-22">
                        <div class="breadcrumbs-bar">
                            {{ Breadcrumbs::render('home') }}
                        </div>
                    </div>
                    <!-- Top right -->
                    <div class="cell top-right-2">
                    </div>
                </div>
            </div>


            <div class="cell small-24 section">
                <div class="owl-carousel home-users-carousel">
                    @foreach($users as $user)
                        <div class="item">
                            <div class="user-container">
                                <img src="/storage/users/avatars/{{ $user->avatar }}" class="user-avatar"
                                     id="user-dots-menu" data-toggler="user-dots-menu">
                            </div>

                            <div class="user-data-group">
                                <div class="grid-x">
                                    <div class="cell small-22">
                                        <a href="#" class="data-user">{{ $user->name }}</a>
                                    </div>
                                    <div class="small-2">
                                        <a href="#">
                                            <img src="files/dots_button.svg">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>


{{--            <div class="cell small-24 section">--}}
{{--                <div class="owl-carousel home-posts-carousel">--}}
{{--                    @foreach($posts as $post)--}}
{{--                        <div class="item">--}}

{{--                            <div class="cell image-unit">--}}
{{--                                @if( !empty($post->image))--}}
{{--                                    <img src="{{ asset('storage/blog/images') . '/' . $post->image }}">--}}
{{--                                @else--}}
{{--                                    <img src="{{ asset('storage/blog/images') . '/' . 'default.jpg' }}">--}}
{{--                                @endif--}}
{{--                            </div>--}}

{{--                            <div class="cell title-unit">--}}
{{--                                <span class="lead">{{ $post->title }}</span>--}}
{{--                            </div>--}}

{{--                            <div class="cell body-unit">--}}
{{--                                <p>{{ substr(strip_tags($post->body), 0, 78) }}{{ strlen(strip_tags($post->body)) > 80 ? "..." : "" }}</p>--}}
{{--                            </div>--}}

{{--                            <div class="cell category-unit">--}}
{{--                                <p>{{ $post->category['name'] }}</p>--}}
{{--                            </div>--}}

{{--                            <div class="cell user-unit">--}}
{{--                                <img src="/storage/users/avatars/{{ $post->user['avatar'] }}" class="post-user-avatar">--}}
{{--                                <span>{{ $post->user['name'] }}</span>--}}
{{--                            </div>--}}

{{--                            <p>{{ $post->created_at->format('F d, Y') }}</p>--}}

{{--                            <div class="tag-label-container">--}}
{{--                                @foreach ($post->tags as $tag)--}}
{{--                                    <a href="{{route('tags.show', $tag->id)}}">--}}
{{--                                        <span class="tag-shape">{{ $tag->name }}</span>--}}
{{--                                    </a>--}}
{{--                                @endforeach--}}
{{--                            </div>--}}

{{--                            <a href="{{ url('blog/'.$post->slug) }}" class="read-more-button">--}}
{{--                                @include('partials.svg.angle-right')--}}
{{--                                {{__('Lees meer') }}--}}
{{--                            </a>--}}

{{--                            <span>{{ read_time($post->body) }}</span>--}}

{{--                        </div>--}}
{{--                    @endforeach--}}
{{--                </div>--}}
{{--            </div>--}}

{{--            <div class="cell small-24 section">--}}
{{--                @foreach($categories as $category)--}}
{{--                    <a href="{{ route('categories.show', $category->id) }}">--}}
{{--                        <span class="category-shape">{{ $category->name }}</span>--}}
{{--                    </a>--}}
{{--                @endforeach--}}
{{--            </div>--}}


{{--            <div class="cell small-24 section">--}}
{{--                @foreach($tags as $tag)--}}
{{--                    <a href="{{ route('tags.show', $tag->id) }}">--}}
{{--                        <span class="tag-shape">{{ $tag->name }}</span>--}}
{{--                    </a>--}}
{{--                @endforeach--}}
{{--            </div>--}}



        </div>
    </div>
@endsection

resources/views/profile.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('classes')
    class="profile"
@endsection

@section('content')
    <div class="grid-x">


        <div class="cell small-24">
            <div class="grid-x grid-margin-x user-credits" >
                <div class="cell small-24 medium-12">
                    <img src="/storage/users/avatars/{{ Auth::user()->avatar }}" class="user-avatar">
                </div>


                <div class="cell small-24 medium-13">
                    <form enctype="multipart/form-data" action="{{ route('profile.update') }}" method="POST">
                        <label>Update Profile Image</label>
                        <input type="file" name="avatar">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="button save"><i class="fas fa-save"></i> Save</button>
                    </form>
                </div>

                <div class="cell small-24 medium-12">

                    <label>Name:</label>
                    <p class="lead">{{ Auth::user()->name }}</p>

                    <label>Email:</label>
                    <p class="lead">{{ Auth::user()->email }}</p>

                    <label>Member since:</label>
                    <p class="lead">{{ Auth::user()->created_at->format('F d, Y') }}</p>


                </div>
            </div>
        </div>


    </div>
@endsection