routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'HomeController@index')->name('home');


/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::get('profile', 'UserProfileController@show')->middleware('auth')->name('profile.show');
Route::post('profile', 'UserProfileController@update_avatar')->middleware('auth')->name('profile.update');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


/*
|--------------------------------------------------------------------------
| Blog Routes
|--------------------------------------------------------------------------
*/

//  Index
Route::get('blog', 'Blog\BlogController@index')->name('blog.index');

//  Single
Route::get('blog/{slug}', 'Blog\BlogController@single')->where('slug', '[\w\d\-\_]+')->name('blog.single');


/*
 * | Posts
|--------------------------------------------------------------------------
*/

//  Resource
Route::resource('posts', 'Blog\PostController');


//  Index
//Route::get('blog/posts', 'Blog\PostController@index')->name('blog.posts.index');

//  Create
Route::get('create', 'Blog\PostController@create');

//  Store
Route::get('store', function () {
    return view('blog.posts.store');
});

//  Show
Route::get('show', function () {
    return view('blog.posts.show');
});


//

Route::get('webshop', function () {
    return view('webshop.index');
});


/*
 * | Comments
|--------------------------------------------------------------------------
*/

Route::post('comments/{post_id}', ['uses' => 'Blog\CommentsController@store', 'as' =>'comments.store']);
Route::get('comments/{id}/edit', ['uses' => 'Blog\CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}', ['uses' => 'Blog\CommentsController@update', 'as' => 'comments.update']);
Route::get('comments/{id}/delete', ['uses' => 'Blog\CommentsController@delete', 'as' => 'comments.delete']);
Route::delete('comments/{id}', ['uses' => 'Blog\CommentsController@destroy', 'as' => 'comments.destroy']);



/*
 * | Categories
|--------------------------------------------------------------------------
*/

Route::resource('categories', 'Blog\CategoryController', ['except' => ['create']]);



/*
 * | Tags
|--------------------------------------------------------------------------
*/

Route::get('tags/find', 'Blog\TagController@find');
Route::resource('tags', 'Blog\TagController', array('except' => array('create', 'find')));

Route::get('pages/check_slug', 'SlugController@check')->name('pages.check_slug');



// Ajax Routes
Route::get('entry', function () {
    return view('auth.entry');
});

Route::get('profile-menu', function(){
    return view('partials.menu.profile-menu');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Post extends Model
{


    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

}

app/Http/Controllers/Blog/BlogController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Category;
use App\Tag;
use App\Post;
use App\User;


class BlogController extends Controller
{

    public function hasCommentsFromUser($userId){
        return $this->comments()->where('user_id', $userId)->count() > 0;
    }

    public function index() {

        // Fetch all posts in desc order and paginate
        $posts = Post::latest('created_at')->paginate(48);
        $users = User::all();
        $categories = Category::all();
        $tags = Tag::all();

        // return the view and pass in the post object
        return view('blog.index', compact('posts', 'users', 'tags', 'categories'));
    }


    public function single($slug) {

        // fetch from the DB based on slug
        $post = Post::where('slug', '=', $slug)->first();
        $user = User::all();
        $categories = Category::all();
        $tags = Tag::all();

        // return the view and pass in the post object
        return view('blog.single', compact('post', 'user', 'tags', 'categories'));

    }

//    /**
//     * Returns an estimated reading time in a string
//     * idea from @link http://briancray.com/posts/estimated-reading-time-web-design/
//     * @param  string $content the content to be read
//     * @return string          estimated read time eg. 1 minute, 30 seconds
//     */
//    function estimate_reading_time($content) {
//        $word_count = str_word_count(strip_tags($content));
//
//        $minutes = floor($word_count / 200);
//        $seconds = floor($word_count % 200 / (200 / 60));
//
//        $str_minutes = ($minutes == 1) ? "minute" : "minutes";
//        $str_seconds = ($seconds == 1) ? "second" : "seconds";
//
//        if ($minutes == 0) {
//            return "{$seconds} {$str_seconds}";
//        }
//        else {
//            return "{$minutes} {$str_minutes}, {$seconds} {$str_seconds}";
//        }
//    }

}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use App\Category;
use Illuminate\Http\Request;
use Session;
use App\Tag;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $tags = Tag::all();
        $categories = Category::all();

        return view('blog.categories.index', compact('categories', 'tags'));

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, array(
            'name' => 'required|max:255'
        ));

        $category = new Category;

        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'New Category has been created');

        return redirect()->route('categories.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        $tags = Tag::all();

        return view('blog.categories.show', compact('category', 'tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $categories = Category::all();

        return view('blog.categories.edit', compact('category', 'categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $this->validate($request, ['name' => 'required|max:255']);

        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'Successfully saved your new tag!');

        return redirect()->route('categories.show', $category->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Find the post in the database
        $category = Category::find($id);
        $category->posts();

        // Delete the post
        $category->delete();

        // Flash data with success message
        Session::flash('success', 'Data destroyed');

        // redirect with flash data to posts.show
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/Blog/CommentsController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Comment;
use App\Post;
use Session;

class CommentsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => 'store']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $post_id)
    {
        $this->validate($request, array(
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
            'comment' => 'required|min:5|max:4028'
        ));

        $post = Post::find($post_id);


        $comment = new Comment();
        $comment->name = $request->name;
        $comment->email = $request->email;
        $comment->comment = $request->comment;
        $comment->approved = true;
        $comment->post()->associate($post);

        $comment->save();

        Session::flash('success', 'Comment Succesfully added');

        return redirect()->route('blog.single', [$post->slug]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::find($id);
        return view('blog.comments.edit')->withComment($comment);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);

        $this->validate($request, array('comment' => 'required'));

        $comment->comment = $request->comment;
        $comment->save();

        Session::flash('success', 'Comment updated');

        return redirect()->route('posts.show', $comment->post->id);
    }

    public function delete($id)
    {
        $comment = Comment::find($id);
        return view('blog.comments.delete')->withComment($comment);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        $post_id = $comment->post->id;
        $comment->delete();

        Session::flash('success', 'Deleted Comment');

        return redirect()->route('posts.show', $post_id);
    }
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Mews\Purifier\Purifier;
use App\User;
use App\Post;
use App\Category;
use App\Tag;
use App\Slug;
use Image;
use Session;
use Mtownsend\ReadTime\ReadTime;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    public function check_slug(Request $request)
    {
        // New version: to generate unique slugs
        $slug = SlugService::createSlug(Post::class, 'slug', $request->title);

        return response()->json(['slug' => $slug]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::orderBy('id', 'desc') -> paginate(5);
        $categories = Category::all();
        $tags = Tag::all();

        return view('blog.posts.index', compact('posts', 'categories', 'tags'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        $categories = Category::all();

        return view('blog.posts.create')->withCategories($categories)->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // validate the data
        $this->validate($request, array(
            'title' => 'required|max:255',
            'category_id' => 'required|integer',
            'slug'  => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'body'  => 'required',
            'featured_image' => 'sometimes|image'
        ));

        // Store in database
        $post = new Post;
        $post->user_id = auth()->id();
        $post->category_id = $request->category_id;
        $post->Title = $request->title;
        $post->slug = $request->slug;
        $post->body = (clean($request->body));

        if ($request->hasFile('featured_image')) {
            $image = $request->file('featured_image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('storage/blog/images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            $post->image = $filename;
        }



        $post->save();

        $post->tags()->sync($request->tags, false);

        Session::flash('success', 'Data Successfully inserted');

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        $user = User::find($id);
        $categories = Category::all();
        $tags = Tag::all();


        return view('blog.posts.show', compact('post', 'user', 'categories', 'tags'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $categories = Category::all();
        $tags = Tag::all();

        $tagsArray = array();
        foreach($tags as $tag) {
            $tagsArray[$tag->id] = $tag->name;
        }

        return view('blog.posts.edit', compact('post', 'categories', 'tags'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate the data
        $post = Post::find($id);

        $this->validate($request, array(
            'title' => 'required|max:255',
            'slug'  => "required|alpha_dash|min:5|max:255|unique:posts,slug,$id",
            'body'  => 'required',
            'featured_image' => 'image'
        ));


        // Save the data to the database
        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->category_id = $request->input('category_id');
        $post->body = (clean($request->input('body')));


        if ($request->hasFile('featured_image')) {

            // add the new photo
            $image = $request->file('featured_image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('storage/blog/images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            // get filename
            $oldFilename = $post->image;

            // update the new photo
            $post->image = $filename;

            // delete the old photo
            Storage::delete($oldFilename);

        }

        $post->save();

        $post->tags()->sync($request->tags, true);

        // set flash data with success message
        Session::flash('success', 'Data Successfully updated');

        // redirect with flash data to posts.show
        return redirect()->route('posts.show', $post->id);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Find the post in the database
        $post = Post::find($id);
        $post->tags()->detach();
        Storage::delete($post->image);

        // Delete the post
        $post->delete();

        // Flash data with success message
        Session::flash('success', 'Data destroyed');

        // redirect with flash data to posts.show
        return redirect()->route('posts.index');
    }
}

resources/views/blog/posts/edit.blade.php
@extends('layouts.app')

@section('title', 'Posts | Edit')

@section('classes')
    class="edit"
@endsection

@section('stylesheets')
    {{--    Exception   --}}
    <script src="//cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'link'
        })
    </script>
    <link rel="stylesheet" type="text/css" href="{{asset('css/vendors/parsely.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/vendors/select2.css') }}">
@endsection


@section('content')
<div class="grid-x grid-margin-x grid-margin-y">

    <div class="cell small-24">
        <div class="grid-x grid-block">
            <!-- Top left -->
            <div class="cell top-left-22">
                <div class="breadcrumbs-bar">
                    <a href="{{ url()->previous() }}" class="go-back">
                        <img src="{{ asset('files/line-angle-left.svg') }}">
                        <span>{{ __('Back') }}</span>
                    </a>
                    {{ Breadcrumbs::render('blog_single', $post) }}
                </div>
            </div>
            <!-- Top right -->
            <div class="cell top-right-2">

            </div>
        </div>
    </div>


    <div class="cell small-24 medium-18">
        <form method="POST" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data" data-parsley-validate>
            <input type="hidden" name="_method" value="PUT">

            <div class="form-group">
                <label name="title">Title:</label>
                <input type="text" id="title" name="title" class="form-control" required value="{{ $post->title }}">
            </div>

            <div class="form-group">
                <label name="slug">Slug:</label>
                <input type="text" name="slug" minlength="5" maxlength="255" required value="{{ $post->slug }}">
            </div>

            <div class="form-group">
                <label name="category_id">Category:</label>
                <select id="category_id" name="category_id">
                    @foreach ($categories as $category)
                        <option {{ ($category->id == $post->category_id) ? 'selected' : '' }} value="{{ $category->id }}">
                            {{ $category->name }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label name="tag_id">Tags:</label>
                <select name="tags[]" class="select2-multi" multiple="multiple">
                    @foreach($tags as $tag)
                        <option value="{{ $tag['id'] }}" >{{ $tag['name'] }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="featured_image">Update Featured Image</label>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <input type="file" id="featured_image" name="featured_image">
            </div>

            <div class="form-group">
                <label name="body">Body:</label>
                <textarea id="body" name="body" rows="10" required>{{ $post->body }}</textarea>
            </div>

            <div class="component-button">
                <input type="submit" value="Save changes" class="save">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </div>
        </form>
    </div>

    <div class="cell small-24 medium-6">

        <dl class="dl-horizontal">
            <dt>Category:</dt>
            <dd><span class="category-shape">{{ $post->category['name'] }}</span></dd>
        </dl>


{{--        <dl class="dl-horizontal">--}}
{{--            <dt>Tags:</dt>--}}
{{--            <dd><span class="tag-shape"></span></dd>--}}
{{--        </dl>--}}

        <dl class="dl-horizontal">
            <dt>Created At:</dt>
            <dd>{{ $post->created_at->format('F d, Y') }}</dd>
        </dl>

        <dl class="dl-horizontal">
            <dt>Last Updated:</dt>
            <dd>{{$post->updated_at->format('F d, h:ia')}}</dd>
        </dl>

        <div class="component-button">
            <a href="{{ route('posts.destroy', $post->id) }}" class="button delete">Cancel</a>
        </div>
    </div>

</div>
@endsection


@section('scripts')
    <script src="{{ asset('js/vendors/parsely.js') }}"></script>
    <script src="{{ asset('js/vendors/select2.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.select2-multi').select2().val({!! json_encode($post->tags()->allRelatedIds()) !!}).trigger('change');
        });
    </script>
@endsection

resources/views/blog/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Posts | Index')

@section('classes')
    class="posts"
@endsection


@section('content')
    <div class="grid-x grid-margin-y">


        <div class="cell small-24">
            <div class="grid-x grid-block">
                <!-- Top left -->
                <div class="cell top-left-22">
                    <div class="breadcrumbs-bar">
                        <a href="{{ url()->previous() }}" class="go-back">
                            <img src="{{ asset('files/line-angle-left.svg') }}">
                            <span>{{__('Back')}}</span>
                        </a>
                        {{ Breadcrumbs::render('create') }}
                    </div>
                </div>
                <!-- Top right -->
                <div class="cell top-right-2">

                </div>
            </div>
        </div>


        <div class="cell small-24 section">

            <div class="section text-right">
                {!! $posts->links('pagination::foundation-6'); !!}
            </div>

            <table class="unstriped stacked data-table">
                <thead>
                    <th>#</th>
                    <td>User</td>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Body</th>
                    <th>Category</th>
                    <th>Tags</th>
                    <th>Slug</th>
                    <th>Created</th>
                    <th>Updated</th>
                </thead>
                <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <th>{{ $post->id }}</th>
                        <td class="td-user">
                            <img src="/storage/users/avatars/{{ $post->user['avatar'] }}" class="post-user-avatar">
                            <span>{{ $post->user['name'] }}</span>
                        </td>
                        <td>
                            @if( !empty($post->image))
                                <img src="{{ asset('storage/blog/images') . '/' . $post->image }}">
                            @else
                                <img src="{{ asset('storage/blog/images') . '/' . 'default.jpg' }}">
                            @endif
                        </td>
                        <td>{{ $post->title }}</td>
                        <td>{{ substr(strip_tags($post->body), 0, 78) }}{{ strlen(strip_tags($post->body)) > 50 ? "..." : "" }}</td>
                        <td>{{ $post->category['name'] }}</td>
                        <td>
                            @foreach($post->tags as $tag)
                                <a href="{{ route('tags.show', $tag->id) }}">
                                    <span class="tag-shape">{{ $tag->name }}</span>
                                </a>
                            @endforeach
                        </td>
                        <td>{{ $post->slug }}</td>
                        <td>{{ $post->created_at->format('F d, Y') }}</td>
                        <td>{{ $post->updated_at->format('F d, h:ia') }}</td>
                        <td>
                            <div class="component-button">
                                <a href="{{ route('posts.show', $post->id) }}" class="show">View</a>
                            </div>
                            <div class="component-button">
                                <a href="{{ route('posts.edit', $post->id) }}" class="edit">Edit</a>
                            </div>
                            <form action="{{ route('posts.destroy', $post->id) }}" method="post">
                                <div class="component-button">
                                    <input type="submit" class="delete" value="Delete">
                                </div>
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                {{method_field('DELETE')}}
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="section text-right">
                {!! $posts->links('pagination::foundation-6'); !!}
            </div>

        </div>

    </div>
@endsection

resources/views/blog/posts/show.blade.php
@extends('layouts.app')

@section('title', 'Show')

@section('stylesheets')
    <link rel="stylesheet" type="text/css" href="{{asset('css/vendors/select2.min.css') }}">
@endsection

@section('classes')
    class="show"
@endsection

@section('content')
    <div class="grid-x grid-margin-x">

        <div class="cell small-24">
            <div class="grid-x grid-block">
                <!-- Top left -->
                <div class="cell top-left-22">
                    <div class="breadcrumbs-bar">
                        <a href="{{ url()->previous() }}" class="go-back">
                            <img src="{{ asset('files/line-angle-left.svg') }}">
                            <span>{{ __('Back') }}</span>
                        </a>
                        {{ Breadcrumbs::render('blog_single', $post) }}
                    </div>
                </div>
                <!-- Top right -->
                <div class="cell top-right-2">

                </div>
            </div>
        </div>


        <div class="cell small-18">
            <div class="featured-image">
                <img src="{{ asset('storage/blog/images') . '/' . $post->image }}">
            </div>
            <h1>{{ $post->title }}</h1>
            <p class="lead">{!! $post->body !!}</p>
        </div>


        <div class="cell small-6">

            <dl class="dl-horizontal">
                <dt>Url:</dt>
                <dd><a href="{{ route('blog.single', $post->slug) }}">{{ route('blog.single', $post->slug) }}</a></dd>
            </dl>

            <dl class="dl-horizontal">
                <dt>Category: </dt>
                <dd>{{ $post->category['name']  }}</dd>
            </dl>

            <dl class="dl-horizontal tags">
                <dt>Tags:</dt>
                @foreach ($post->tags as $tag)
                    <a href="{{ route('tags.show', $tag->id) }}"><span class="tag-shape">{{ $tag->name }}</span></a>
                @endforeach
            </dl>

            <dl class="dl-horizontal">
                <dt>Created:</dt>
                <dd>{{ $post->created_at->format('F d, Y') }}</dd>
            </dl>

            <dl class="dl-horizontal">
                <dt>Updated:</dt>
                <dd>{{$post->updated_at->format('F d, h:ia')}}</dd>
            </dl>

            <div class="component-button">
                <a href="{{ route('posts.edit', $post->id) }}" class="edit">Edit</a>
            </div>

            <form action="{{ route('posts.destroy', $post->id) }}" method="post">
                <div class="component-button">
                    <input type="submit" value="Delete" class="delete">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{method_field('DELETE')}}
                </div>
            </form>

        </div>

        <div class="cell small-24" id="backend-comments">
            <h3>Comments <small>{{ $post->comments()->count() }}</small></h3>
            <table class="stacked unstriped">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Comment</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($post->comments as $comment)
                    <tr>
                        <td>{{ $comment->name }}</td>
                        <td>{{ $comment->email }}</td>
                        <td>{!!  $comment->comment !!}</td>
                        <td>
                            <a href="{{ route('comments.edit', $comment -> id) }}" class="button edit">
                                <span>Edit</span>
                            </a>
                            <a href="{{ route('comments.delete', $comment -> id) }}" class="button delete">
                                <span>Delete</span>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/vendors/select2.full.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.select2-multi').select2();
        });
    </script>
@endsection