routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'HomeController@index')->name('home');


/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::get('profile', 'UserProfileController@show')->middleware('auth')->name('profile.show');
Route::post('profile', 'UserProfileController@update_avatar')->middleware('auth')->name('profile.update');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


/*
|--------------------------------------------------------------------------
| Blog Routes
|--------------------------------------------------------------------------
*/

//  Index
Route::get('blog', 'Blog\BlogController@index')->name('blog.index');

//  Single
Route::get('blog/{slug}', 'Blog\BlogController@single')->where('slug', '[\w\d\-\_]+')->name('blog.single');


/*
 * | Posts
|--------------------------------------------------------------------------
*/

//  Resource
Route::resource('posts', 'Blog\PostController');


//  Index
//Route::get('blog/posts', 'Blog\PostController@index')->name('blog.posts.index');

//  Create
Route::get('create', 'Blog\PostController@create');

//  Store
Route::get('store', function () {
    return view('blog.posts.store');
});

//  Show
Route::get('show', function () {
    return view('blog.posts.show');
});


//

Route::get('webshop', function () {
    return view('webshop.index');
});


/*
 * | Comments
|--------------------------------------------------------------------------
*/

Route::post('comments/{post_id}', ['uses' => 'Blog\CommentsController@store', 'as' =>'comments.store']);
Route::get('comments/{id}/edit', ['uses' => 'Blog\CommentsController@edit', 'as' => 'comments.edit']);
Route::put('comments/{id}', ['uses' => 'Blog\CommentsController@update', 'as' => 'comments.update']);
Route::get('comments/{id}/delete', ['uses' => 'Blog\CommentsController@delete', 'as' => 'comments.delete']);
Route::delete('comments/{id}', ['uses' => 'Blog\CommentsController@destroy', 'as' => 'comments.destroy']);



/*
 * | Categories
|--------------------------------------------------------------------------
*/

Route::resource('categories', 'Blog\CategoryController', ['except' => ['create']]);



/*
 * | Tags
|--------------------------------------------------------------------------
*/

Route::get('tags/find', 'Blog\TagController@find');
Route::resource('tags', 'Blog\TagController', array('except' => array('create', 'find')));

Route::get('pages/check_slug', 'SlugController@check')->name('pages.check_slug');



// Ajax Routes
Route::get('entry', function () {
    return view('auth.entry');
});

Route::get('profile-menu', function(){
    return view('partials.menu.profile-menu');
});

app/Tag.php
<?php

namespace App;

//use Illuminate\Database\Eloquent\Model;
//use Sofa\Eloquence\Eloquence;
//
//class Tag extends Model
//{
//
//    public function posts()
//    {
//        return $this->belongsToMany('App\Post');
////        return $this->hasMany(Post::class); // also Post belongsToMany Categories
//
//    }
//}

use Illuminate\Database\Eloquent\Model;
use Sofa\Eloquence\Eloquence;

class Tag extends Model
{
    use Eloquence;

    protected $searchableColumns = ['name'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name'];

        public function posts()
    {
        return $this->belongsToMany('App\Post');

    }
}

app/Http/Controllers/Blog/BlogController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Category;
use App\Tag;
use App\Post;
use App\User;


class BlogController extends Controller
{

    public function hasCommentsFromUser($userId){
        return $this->comments()->where('user_id', $userId)->count() > 0;
    }

    public function index() {

        // Fetch all posts in desc order and paginate
        $posts = Post::latest('created_at')->paginate(48);
        $users = User::all();
        $categories = Category::all();
        $tags = Tag::all();

        // return the view and pass in the post object
        return view('blog.index', compact('posts', 'users', 'tags', 'categories'));
    }


    public function single($slug) {

        // fetch from the DB based on slug
        $post = Post::where('slug', '=', $slug)->first();
        $user = User::all();
        $categories = Category::all();
        $tags = Tag::all();

        // return the view and pass in the post object
        return view('blog.single', compact('post', 'user', 'tags', 'categories'));

    }

//    /**
//     * Returns an estimated reading time in a string
//     * idea from @link http://briancray.com/posts/estimated-reading-time-web-design/
//     * @param  string $content the content to be read
//     * @return string          estimated read time eg. 1 minute, 30 seconds
//     */
//    function estimate_reading_time($content) {
//        $word_count = str_word_count(strip_tags($content));
//
//        $minutes = floor($word_count / 200);
//        $seconds = floor($word_count % 200 / (200 / 60));
//
//        $str_minutes = ($minutes == 1) ? "minute" : "minutes";
//        $str_seconds = ($seconds == 1) ? "second" : "seconds";
//
//        if ($minutes == 0) {
//            return "{$seconds} {$str_seconds}";
//        }
//        else {
//            return "{$minutes} {$str_minutes}, {$seconds} {$str_seconds}";
//        }
//    }

}

app/Http/Controllers/Blog/CategoryController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use App\Category;
use Illuminate\Http\Request;
use Session;
use App\Tag;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $tags = Tag::all();
        $categories = Category::all();

        return view('blog.categories.index', compact('categories', 'tags'));

    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, array(
            'name' => 'required|max:255'
        ));

        $category = new Category;

        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'New Category has been created');

        return redirect()->route('categories.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);
        $tags = Tag::all();

        return view('blog.categories.show', compact('category', 'tags'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        $categories = Category::all();

        return view('blog.categories.edit', compact('category', 'categories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $this->validate($request, ['name' => 'required|max:255']);

        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'Successfully saved your new tag!');

        return redirect()->route('categories.show', $category->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Find the post in the database
        $category = Category::find($id);
        $category->posts();

        // Delete the post
        $category->delete();

        // Flash data with success message
        Session::flash('success', 'Data destroyed');

        // redirect with flash data to posts.show
        return redirect()->route('categories.index');
    }
}

app/Http/Controllers/Blog/CommentsController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use App\Comment;
use App\Post;
use Session;

class CommentsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => 'store']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $post_id)
    {
        $this->validate($request, array(
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
            'comment' => 'required|min:5|max:4028'
        ));

        $post = Post::find($post_id);


        $comment = new Comment();
        $comment->name = $request->name;
        $comment->email = $request->email;
        $comment->comment = $request->comment;
        $comment->approved = true;
        $comment->post()->associate($post);

        $comment->save();

        Session::flash('success', 'Comment Succesfully added');

        return redirect()->route('blog.single', [$post->slug]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::find($id);
        return view('blog.comments.edit')->withComment($comment);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);

        $this->validate($request, array('comment' => 'required'));

        $comment->comment = $request->comment;
        $comment->save();

        Session::flash('success', 'Comment updated');

        return redirect()->route('posts.show', $comment->post->id);
    }

    public function delete($id)
    {
        $comment = Comment::find($id);
        return view('blog.comments.delete')->withComment($comment);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $comment = Comment::find($id);
        $post_id = $comment->post->id;
        $comment->delete();

        Session::flash('success', 'Deleted Comment');

        return redirect()->route('posts.show', $post_id);
    }
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Mews\Purifier\Purifier;
use App\User;
use App\Post;
use App\Category;
use App\Tag;
use App\Slug;
use Image;
use Session;
use Mtownsend\ReadTime\ReadTime;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }


    public function check_slug(Request $request)
    {
        // New version: to generate unique slugs
        $slug = SlugService::createSlug(Post::class, 'slug', $request->title);

        return response()->json(['slug' => $slug]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $posts = Post::orderBy('id', 'desc') -> paginate(5);
        $categories = Category::all();
        $tags = Tag::all();

        return view('blog.posts.index', compact('posts', 'categories', 'tags'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        $categories = Category::all();

        return view('blog.posts.create')->withCategories($categories)->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // validate the data
        $this->validate($request, array(
            'title' => 'required|max:255',
            'category_id' => 'required|integer',
            'slug'  => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
            'body'  => 'required',
            'featured_image' => 'sometimes|image'
        ));

        // Store in database
        $post = new Post;
        $post->user_id = auth()->id();
        $post->category_id = $request->category_id;
        $post->Title = $request->title;
        $post->slug = $request->slug;
        $post->body = (clean($request->body));

        if ($request->hasFile('featured_image')) {
            $image = $request->file('featured_image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('storage/blog/images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            $post->image = $filename;
        }



        $post->save();

        $post->tags()->sync($request->tags, false);

        Session::flash('success', 'Data Successfully inserted');

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        $user = User::find($id);
        $categories = Category::all();
        $tags = Tag::all();


        return view('blog.posts.show', compact('post', 'user', 'categories', 'tags'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $categories = Category::all();
        $tags = Tag::all();

        $tagsArray = array();
        foreach($tags as $tag) {
            $tagsArray[$tag->id] = $tag->name;
        }

        return view('blog.posts.edit', compact('post', 'categories', 'tags'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // Validate the data
        $post = Post::find($id);

        $this->validate($request, array(
            'title' => 'required|max:255',
            'slug'  => "required|alpha_dash|min:5|max:255|unique:posts,slug,$id",
            'body'  => 'required',
            'featured_image' => 'image'
        ));


        // Save the data to the database
        $post = Post::find($id);
        $post->title = $request->input('title');
        $post->slug = $request->input('slug');
        $post->category_id = $request->input('category_id');
        $post->body = (clean($request->input('body')));


        if ($request->hasFile('featured_image')) {

            // add the new photo
            $image = $request->file('featured_image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('storage/blog/images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            // get filename
            $oldFilename = $post->image;

            // update the new photo
            $post->image = $filename;

            // delete the old photo
            Storage::delete($oldFilename);

        }

        $post->save();

        $post->tags()->sync($request->tags, true);

        // set flash data with success message
        Session::flash('success', 'Data Successfully updated');

        // redirect with flash data to posts.show
        return redirect()->route('posts.show', $post->id);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // Find the post in the database
        $post = Post::find($id);
        $post->tags()->detach();
        Storage::delete($post->image);

        // Delete the post
        $post->delete();

        // Flash data with success message
        Session::flash('success', 'Data destroyed');

        // redirect with flash data to posts.show
        return redirect()->route('posts.index');
    }
}

resources/views/blog/tags/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Tags')

@section('classes')
    class="tags-edit"
@endsection

@section('content')
    <div class="grid-x">

        <div class="cell small-24">
            <div class="grid-x grid-block">
                <!-- Top left -->
                <div class="cell top-left">
                    <div class="breadcrumbs-bar">
                        {{ Breadcrumbs::render('tags') }}
                    </div>
                </div>
                <!-- Top right -->
                <div class="cell top-right">

                </div>
            </div>
        </div>

        <div class="cell small-24">
            <div class="back-bar">
                <a href="{{ url()->previous() }}" class="go-back">
                    <img src="{{ asset('files/line-angle-left.svg') }}">
                    {{ __('Back') }}
                </a>
            </div>
        </div>


        <div class="cell small-12">
            <form action="{{ route('tags.update', $tag->id) }}" method="POST" data-parsley-validate>
                <input type="hidden" name="_method" value="PUT">
                <label>Title:</label>

                <input name="name" type="text" value="{{ $tag->name }}" required>

                <div class="component-button">
                    <input type="submit" class="button" value="Save changes">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/blog/tags/index.blade.php
@extends('layouts.app')

@section('title', 'Blog | Tags')

@section('classes')
    class="tags-index"
@endsection

@section('content')
    <div class="grid-x grid-margin-x grid-margin-y">

        <div class="cell small-24">
            <div class="grid-x grid-block">
                <!-- Top left -->
                <div class="cell top-left">
                    <div class="breadcrumbs-bar">
                        {{ Breadcrumbs::render('tags') }}
                    </div>
                </div>
                <!-- Top right -->
                <div class="cell top-right">

                </div>
            </div>
        </div>

        <div class="cell small-24">
            <div class="back-bar">
                <a href="{{ url()->previous() }}" class="go-back">
                    <img src="{{ asset('files/line-angle-left.svg') }}">
                    {{ __('Back') }}
                </a>
            </div>
        </div>


        <div class="cell small-18">

            <table class="stacked unstriped">
                <thead>
                    <th>#</th>
                    <th>Name</th>
                    <th>Assoc. posts</th>
                </thead>
                <tbody>
                @foreach ($tags as $tag)
                    <tr>
                        <td>{{ $tag->id }}</td>
                        <td><a href="{{ route('tags.show', $tag->id) }}"><span class="tag-shape">{{ $tag->name }}</span></a></td>
                        <td>{{ $tag->posts()->count() }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>

        <div class="cell small-6">

            <form method="POST" action="{{ route('tags.store') }}" data-parsley-validate>
                <div class="form-group">
                    <label name="nane">New Tag</label>
                    <input id="tag" name="name" class="tag" required>
                </div>

                <div class="component-button">
                    <button type="submit" class="button">Create new tag</button>
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                </div>
            </form>
        </div>

    </div>
@endsection

resources/views/blog/tags/show.blade.php
@extends('layouts.app')

@section('title', "Tags")

@section('classes')
    class="show-single-tag"
@endsection


@section('content')
    <div class="grid-x">

        <div class="cell small-24">
            <div class="grid-x grid-block">
                <!-- Top left -->
                <div class="cell top-left">
                    <div class="breadcrumbs-bar">
                        {{ Breadcrumbs::render('tags') }}
                    </div>
                </div>
                <!-- Top right -->
                <div class="cell top-right">

                </div>
            </div>
        </div>

        <div class="cell small-24">
            <div class="back-bar">
                <a href="{{ url()->previous() }}" class="go-back">
                    <img src="{{ asset('files/line-angle-left.svg') }}">
                    {{ __('Back') }}
                </a>
            </div>
        </div>


        <div class="cell small-18">
            <h1>{{ $tag->name }}
                <small>{{ $tag->posts()->count() }} Posts</small>
            </h1>
        </div>

        <div class="cell small-6 action-cell">
            <div class="component-button">
                <a href="{{ route('tags.edit', $tag->id) }}" class="button">Edit</a>
            </div>
            <div class="component-button">
                <form action="{{ route('tags.destroy', $tag->id) }}" method="post">
                    <input type="submit" class="button delete" value="Delete">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{method_field('DELETE')}}
                </form>
            </div>
        </div>

        <div class="cell small-24">
            <table class="stacked unstriped">
                <thead>
                <th>#</th>
                <th>Title</th>
                <th>Tags</th>
                <th>Action</th>
                </thead>
                <tbody>
                @foreach ($tag->posts as $post)
                    <tr>
                        <td>{{ $post->id }}</td>
                        <td>{{ $post->title }}</td>
                        <td>
                            @foreach($post->tags as $tag)
                                <a href="{{ route('tags.show', $tag->id) }}"><span class="tag-shape">{{ $tag->name }}</span></a>
                            @endforeach
                        </td>
                        <td>
                            <div class="component-button">
                                <a href="{{ route('posts.show', $post->id) }}" class="button">View</a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    </div>
@endsection